config/routes.rb
Rails.application.routes.draw do
#  get 'charges/index'

#  get 'charges/show'

#  get 'charges/new'

#  get 'charges/edit'

  resources :wikis do
    member do
      put :add_collaborator
      put :delete_collaborator
    end
  end

  resources :charges, only: [:new, :create]

  devise_for :users
  resources :users, only: [:show] do
    member do
      put :downgrade
    end
  end

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/models/amount.rb
class Amount
  def self.default
    1500
  end
end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable


  before_create { self.role ||= :standard }

  has_many :wikis, dependent: :destroy
  has_many :collaborations
  has_many :collaborating_wikis, through: :collaborations, source: :wiki


  enum role: [:standard, :premium, :admin]

  def downgrade
    self.role = :standard

    wikis.each { |wiki| wiki.make_public }


    self.save

  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborations
  has_many :collaborators, through: :collaborations, source: :user

  scope :visible_to, -> (user) { user ? where(private: false) : 'There was an error.' }

  def make_public
    update_attribute(private: false)
  end

  def public?
    !private?
  end

  def private?
    !!self.private
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!
  # before_action :premium

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attribute(:role, 'premium')

    flash[:notice] = "Your payment has been received, #{current_user.email}. Thank you!"
    redirect_to wikis_path # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      current_user.update_attribute(:role, 'standard')
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.email}",
      amount: Amount.default
    }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @wikis = @user.wikis
  end

  def downgrade
    @user = User.find(params[:id])

    if @user.downgrade
      flash[:notice] = "You've been downgraded to standard. Your private wikis are now public."
      redirect_to wiki_path
    else
      flash[:error] = "There was an error downgrading your account. Please try again."
      redirect_to :back
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!

  def index
    @wikis = Wiki.all
    @wikis = Wiki.visible_to(current_user)

    if current_user.premium? || current_user.admin?
      @wikis = Wiki.all
    end
  end

  def show
     @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
      end
    end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
     @wiki = Wiki.find(params[:id])
     @wiki.assign_attributes(wiki_params)

     if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
     end
   end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  def add_collaborator
    @wiki = Wiki.find(params[:id])
    candidate = User.find_by(email: params[:email])
    @wiki.collaborators.each do |collaborator|
      if collaborator.email == candidate.email
        flash[:alert] = "That user is already a collaborator for the wiki."
        redirect_to wiki_path(@wiki)
        return
      end
    end
    if candidate.email == @wiki.user.email
      flash[:alert] = "That user is the owner of the wiki."
    else
      @wiki.collaborators << candidate
    end
    redirect_to wiki_path(@wiki)
  end

  def delete_collaborator
    @wiki = Wiki.find(params[:id])
    candidate_id = params[:user_id]
    exists = @wiki.collaborators.pluck(:id).include?(candidate_id.to_i)
    if exists
      candidate = User.find(candidate_id)
      @wiki.collaborators.delete(candidate)
      flash[:alert] = "That collaborator was removed."
    else
      flash[:alert] = "That user is not a collaborator for the wiki."
    end
    redirect_to wiki_path(@wiki)
  end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :collaborators)
  end

  def authorize_user
    wiki = Wiki.find(params[:id])
    unless current_user == wiki.user || current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to wikis_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: '_blank' },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = ::Redcarpet::Render::HTML.new(options)
    markdown = ::Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/edit.html.erb
<h1>Charges#edit</h1>
<p>Find me in app/views/charges/edit.html.erb</p>

app/views/charges/index.html.erb
<h1>Charges#index</h1>
<p>Find me in app/views/charges/index.html.erb</p>

app/views/charges/new.html.erb
<h1>Charges#new</h1>
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/charges/show.html.erb
<h1>Charges#show</h1>
<p>Find me in app/views/charges/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "View All Wikis", wikis_path %></li>
      <div class="pull-right user-info">
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
        -
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        -
        <%= link_to 'Account Details', user_path(current_user), :class => 'navbar-link' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>  
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>


    <%= yield %>
  </div>

</body>
</html>

app/views/users/downgrade.html.erb
<h1>Downgrade Your Account</h1>

<div class="row">
  <div class="col-md-8">
    <p>"Are you sure you would like to downgrade your account? Any private wikis will now become public."</p>
  </div>
  <div class="form-group">
    <%= f.submit "Downgrade", class: 'btn btn-success' %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
      <% end %>
      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Sign up", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h3>User Email: <%= markdown(@user.email) %></h3>

<div class="row">
  <div class="col-md-8">
    <h3>Account Type: <%= markdown(@user.role) %></h3>
  </div>
  <div class="col-md-4">
    <% if @user.premium? %>
      <%= link_to 'Downgrade Account', downgrade_user_path(@user), class: 'btn btn-warning', method: :put %>
    <% elsif @user.standard? %>
      <%= link_to 'Upgrade Account', new_charge_path(@user), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to Blocipedia!</h1>
<h2>Create your wikis here!</h2>
<p>Create private wikis if you are a premium user.</p>
<p>Create public wikis for free!</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocipedia!</h1>
<p>Create and share your wikis.</p>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <%= render partial: 'wikis/form', locals: { f: f } %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wikis</h1>

  <div class="row">
    <div class="col-md-8">
      <%= form_for @wiki do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>
        <%= render partial: 'wikis/form', locals: { f: f } %>
        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
  <h2>Collaborators</h2>
  <% @wiki.collaborators.each do |collaborator| %>
    <%= collaborator.email %>
    <%= link_to 'Delete Collaborator', delete_collaborator_wiki_path(@wiki, user_id: collaborator.id), class: 'btn btn-danger',
            method: :put,
            data: { confirm: 'Are you sure you want to delete the collaborator?'} %>
  <% end %>
<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to 'Edit Wiki', edit_wiki_path(@wiki.id), class: 'btn btn-success' %>
    <%= link_to 'Delete Wiki', @wiki, class: 'btn btn-danger',
            method: :delete,
            data: { confirm: 'Are you sure you want to delete your Wiki'} %>
    <%= form_tag add_collaborator_wiki_path(@wiki), method: :put do %>
      <label> Collaborator Email: </label>
    <br>
      <%= email_field_tag 'email' %>
    <br>
      <%= submit_tag "Add Collaborator", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>